name: Terraform Apply
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  apply:
    name: Update
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      # Configure aws creds
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
