name: Terraform Plan
on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: prod
    defaults:
     run:
       shell: bash
       working-directory: ./environments/prod # TODO different paths for target env
    steps:
      - uses: actions/checkout@v4

      # Setup Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "v1.12.2"

      # Configure aws creds
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::691595548805:role/github_actions_full_admin

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform -chdir=environments/prod/infra plan -no-color
        continue-on-error: true
        id: plan
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_email: ${{ secrets.EMAIL }}
          TF_VAR_domain: ${{ secrets.DOMAIN }}
          TF_VAR_github_email: ${{ secrets.EMAIL }}
          TF_VAR_github_pat: ${{ secrets.GH_PAT }}
          TF_VAR_postgres_admin_password: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          TF_VAR_postgres_replication_password: ${{ secrets.POSTGRES_REPLICATION_PASSWORD }}
          TF_VAR_hydra_database_password: ${{ secrets.HYDRA_DATABASE_PASSWORD }}
        run: |
          kubeconfig_path="/tmp/kubeconfig"

      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Terraform Plan Result
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
